### ISSUE TITLE
Error 500 when trying to send the request

### ISSUE THREAD

**Issue by cedricMea** [alipphardt/cdc-wonder-api#2]
Hello @alipphardt . Thank you for the tuto. It helps me a lot. I am trying to reproduce what you did but got a Status code 500 (internal server error). Does the code still work for you ? Do you have an idea of where can the problem comes from ?

Thank you
![Capture](https://user-images.githubusercontent.com/17460244/67471565-e36e0b80-f64f-11e9-9989-094b7fc81656.PNG)

**Comment by alipphardt** [comment]
Error 500 likely means that an invalid request was sent. I would need to see the full details of the request to comment. See the API documentation for restrictions/limitations.

One restriction is that you cannot limit or group by location when querying via the API:

https://wonder.cdc.gov/wonder/help/WONDER-API.html
