### ISSUE TITLE
Code doesnt work for grouping by Location 

### ISSUE THREAD

**Issue by shamleo17** [alipphardt/cdc-wonder-api#4]
Hi alipphardt,
Thank you for the code. 
I ran the code as is and i was able to get the results. However when i try to group by county or any other values which come under Location it gives error as 500 something went wrong.
I used D76.V9-level2 for B_1 and i tried all the other values which fall under Location and i get the same error.
Could you please help me here?

**Comment by alipphardt** [comment]
Per the CDC WONDER API documentation:

"Queries for mortality and births statistics from the National Vital Statistics System cannot limit or group results by any location field, such as Region, Division, State or County, or Urbanization (urbanization categories map to specific geographic counties)."

https://wonder.cdc.gov/wonder/help/WONDER-API.html
